deploy:
  provider: heroku
  api_key:
    secure: ppwyU4CzXIk8LE4n/80WEvi2gdTST8RSgeRWzfjOeqVp1Lp/rLkRD4WIsnjcFsgAHHRROO/mISMxZYzAX8XpObU+sj8arJ/QMyA7HFDLCaCvhq9CESzkEyMMmaXw4tEBd8+flrfLq8sQ2H9C4zlm3NXaRHS0BySrevlQfG+ND9T9OwiNUmUuBgxmJRdYWr85zz3K4pCTH+c8rDajTrpqSvDzXoiiTuzsIr1hQ36CwvpZqKstHN6Sdrxa3+W/PWKSuNZCJEKLvxTZqGQW38J4EtZXb+gL5MR2wbksLj3WSzJsrIHTtKQJeePn78zG2OhgYkSU+5DwkM8lP+zV4q0Us7tf585f5qDNlC3mYD1a+U4UNw2Xzhwpe+kK7NWd2w6gmMbVp4lPErJTZQ71PeJEw7iG51uzsWCJxiuzJ37F5YZ8CPWyilEJ2/PPxqTHKi1V68462TR3wd3B1wZFdoEc1/L6oV2+Wgxtcs6rhBYcHrK6P4J80oEfT3eQZmOC4a2QsbViVemzhbUpCuvWRJKsgHd2DnQInq2cwTR3hEOG8HBqti/FSoV3sVwcd2XH7q5wgJLEQJg+A7l+8c0YSBuEDOS4gqshaElYcyCEcqkVJ3RKwrbsc77wkkDasOPaDsCY+qVq4pMDBWlVPNKFhf8k3B5vCMyaZhKm32b96JS0uOE=
  app: head-lyrics-controller
  on:
    repo: miguelonga/head-lyrics-controller-rails
